import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[cursor]
style = "Underline"
unfocused_hollow = true

[font]
size = 11

[font.bold]
family = "JetBrains Mono NerdFont"
style = "Bold"

[font.italic]
family = "JetBrains Mono NerdFont"
style = "Regular"

[font.normal]
family = "JetBrains Mono NerdFont"
style = "Regular"

[font.offset]
y = 7

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = true

[window.padding]
x = 15
y = 15
